### ISSUE TITLE
Citation Command

### ISSUE THREAD

**Issue by GrandJune** [rschuetzler/latex-icis-template#10]
Hi,

Thanks for this well-designed template. I wonder why you use a new command \autocite{} in this template. Could this command cover other commands like \citet{}, \citep{}, \citeauthor{}, \citeyear{}?

I can't use the commands above in this templated working on Lualatex (the only compiler that works on overleaf). How can I cite the author in the text, like \citet{}?

Thanks!

**Comment by suparna-ghanvatkar** [comment]
Hi, 

Could you try the \textcite{} and \parencite{}? They work fine for me on overleaf.

**Comment by GrandJune** [comment]
Hi,
These two commands work on the Lualatex compiler. Thanks! That's interesting. I can't use XeLatex on my end.
