### ISSUE TITLE
Overleaf Update Question

### ISSUE THREAD

**Issue by T3chTobi** [rschuetzler/latex-icis-template#11]
Thank you for providing this template!

I discovered your Overleaf Template: https://de.overleaf.com/latex/templates/icis-template/btmdqvnbfccg
In this regard, I asked myself if this Overleaf template already includes the latest adaptions to the template from Github?

**Comment by rschuetzler** [comment]
I haven't updated that template since initially posting. But you should be able to take the files from here and make a new project.

**Comment by T3chTobi** [comment]
I tried the replacement of the Overleaf files with the Github files, but I got multiples errors and warnings. Would it be possible for you to update the Overleaf Template?
Thank you in advance!

**Comment by rschuetzler** [comment]
This is the latest version in an Overleaf template https://www.overleaf.com/latex/templates/icis-2022-submission-template/bngjfrfpwjfx

**Comment by T3chTobi** [comment]
Thank you very much!
