### ISSUE TITLE
neither /autocite nor /parentcite gets recognized

### ISSUE THREAD

**Issue by Izabel94** [rschuetzler/latex-icis-template#8]
Hi, it's my first time using XeLatex as compiler, and I followed every step described, but still the citing commands do not get recognized. I am not sure how to spot the error, since I am not getting any. Any help is appreciated, since the deadline is coming :D

**Comment by rschuetzler** [comment]
Do you have the Biber software installed?

**Comment by Izabel94** [comment]
Yes, Biber installed, georgia fonts downloaded. I use latex on overleaf tho, maybe that has something to do with?

**Comment by rschuetzler** [comment]
Could be. I have never used Overleaf.

**Comment by rschuetzler** [comment]
I just imported the project into Overleaf, and the template doc renders fine, including the citaitons.

**Comment by Izabel94** [comment]
Maybe I am supposed to install biber to a specific location? or add an extra command to the file pointing where it is? I just installed mixtex, which is supposed to automatically install it and I get the same problem, so this might not be the issue. Which latex environment do you use?

**Comment by rschuetzler** [comment]
I typically use MikTeX on Windows, or Texlive on mac. Like I said, though, I had it working on Overleaf, so if that's your place, it should work. Just need to make sure you select XeLaTeX compiler
